server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: queryguard-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: queryguard
          __path__: /app/logs/*.log

    pipeline_stages:
      - regex:
          expression: '.*: (?P<json>\{.*\})'

      - json:
          source: json
          expressions:
            type: type
            endpoint: endpoint
            method: method
            traceId: traceId
            queryCount: queryCount
            nplusOneDetected: nplusOneDetected
            overallSeverity: overallSeverity

      - labels:
          type:
          endpoint:
          method:
          nplusOneDetected:
          overallSeverity: