{
 "title": "Query Guard Dashboard -3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Queries (last 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"queryguard\"}[5m]))"
    }
   ]
  },
  {
   "title": "N+1 Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"queryguard\"} |= \"nplusOneDetected\\\":true\"[$__range]))"
    }
   ]
  },
  {
   "title": "Critical Issues Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"queryguard\"} |= \"overallSeverity\\\":\\\"CRITICAL\\\"\"[$__range]))"
    }
   ]
  },
  {
   "title": "Total Requests vs Problematic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time({job=\"queryguard\", type=\"QUERY_GUARD\"}[$__range])\n)",
     "legendFormat": "All Requests"
    },
    {
     "expr": "sum(\n  count_over_time({job=\"queryguard\", nplusOneDetected=\"true\"}[$__range])\n)",
     "legendFormat": "Problematic Requests"
    }
   ]
  },
  {
   "title": "Top Problamatic Endpoints",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (endpoint) (\n    count_over_time({job=\"queryguard\", nplusOneDetected=\"true\"}[$__range])\n  )\n)"
    }
   ]
  },
  {
   "title": "Severity Distribution",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (overallSeverity) (\n  count_over_time({job=\"queryguard\", type=\"QUERY_GUARD\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "N+1 Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"queryguard\"} |= \"nplusOneDetected\\\":true\"[$__range]))"
    }
   ]
  }
 ]
}